---
title: "Cost coloring of bipartite graphs"
output:
  html_notebook:
    theme: united
    toc: yes
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

# Init
```{r cho = T, results = 'hide'}
library(igraph)
library(parallel)
library(tictoc)

source("src/3-pseudocoloring.R")
source("src/2-coloring.R")
source("src/is_colored_properly.R")
source("src/sum_coloring.R")
source("src/27_26-approximate-coloring.R")
source("src/brute_force.R")
source("src/is_optimal.R")
```
# Reference input
```{r}
c <- c(1,2,3,4)
# g <- read.graph("graphs/bipartite.graphml", "graphml")
g <- read.graph("test0407/6-3.graphml", "graphml")
V(g)$color <- 1

# setEPS()
# postscript("graphs/reference_graph.eps", fonts = c("serif"))
plot(g, layout=layout_as_bipartite, main='input graph', vertex.size=40, vertex.label.cex=1, vertex.label = paste(V(g)$name, '/', V(g)$weight))
# dev.off()
```
# 3-pseudocoloring
```{r}
tic("3-pseudocoloring")
threePseudocoloring <- three_pseudocoloring(g, c, TRUE)
toc()

threePseudocoloring
V(g)[threePseudocoloring[[1]]]$color <- c[1]
V(g)[threePseudocoloring[[2]]]$color <- c[2]

if (length(threePseudocoloring) == 3) {
  V(g)[threePseudocoloring[[3]]]$color <- c[3]
}

sum <- sum_coloring(g, c)
result_print(g, sum)
```
# Test 27/26-algorithm
```{r}
tic("27/26-approximate algorithm")
result <- four_coloring(g, c, TRUE)
toc()

S <- result[[1]]
Ssum <- result[[2]]

result_print(S, Ssum)
```
# Brute force test
```{r}
tic('Brute force')
B <- brute_force(g, c, Ssum)
toc()

result_print(B[[1]], B[[2]])
```
# Test 1
```{r}
tic('test')
n <- 8
density <- c(0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
df <- data.frame()

for (i in 1:length(density)) {
  path <- paste0('test0704/', i)
  if (!dir.exists(path))
    dir.create(path)
  
  for(j in 1:500) {
    graph <- sample_bipartite(n/2, n/2, p=density[i])
    V(graph)$weight <- sample(c(1,2,6,24), n, replace = TRUE)
    V(graph)$name <- letters[1:n]
    
    approximated <- four_coloring(graph, c)
    bruteForced <- brute_force(graph, c, approximated[[2]])

    V(graph)$color = V(approximated[[1]])$color
    V(graph)$color2 = V(bruteForced[[1]])$color
    graph$approximated = approximated[[2]]
    graph$optimal = bruteForced[[2]]
    
    df <- rbind(df, data.frame(list(group = i, counter = j, density = density[i], approximated = approximated[[2]], optimal = bruteForced[[2]], ratio = approximated[[2]] / bruteForced[[2]])))
    
    write_graph(graph, paste0('test0704/', i ,'-', j, '.graphml'), "graphml")
  }
}
toc()

saveRDS(df, file = 'test0704/data.rds')
```
# Playing with data frame
```{r}
df <- readRDS(file = 'test0407/data.rds')
invalids <- df[df$ratio > 27/26,]
invalids
```
```{r}
fixed <- data.frame()
tic('fixing')
for (i in 1:nrow(invalids)) {
# for (i in 1:1) {
  group <- invalids[i,1]
  counter <- invalids[i,2]
  g <- read.graph(paste0('test0407/', group, '-', counter,'.graphml'), "graphml")
  
  approximated <- four_coloring(g, c)
  bruteForced <- brute_force(g, c, approximated[[2]])
  
  V(g)$color = V(approximated[[1]])$color
  V(g)$color2 = V(bruteForced[[1]])$color
  g$approximated = approximated[[2]]
  g$optimal = bruteForced[[2]]
  g$ratio = g$approximated / g$optimal
  
  fixed <- rbind(fixed, data.frame(list(group = group, counter = counter, density = invalids[i,3], approximated = approximated[[2]], optimal = bruteForced[[2]], ratio = approximated[[2]] / bruteForced[[2]])))
  
  write_graph(g, paste0('test0407/fixed/', group ,'-', counter, '.graphml'), "graphml")
  break
}

toc()
saveRDS(fixed, file = 'test0407/fixed.rds')

```
```{r}
fixed[fixed$ratio > 1,]
```
# Compare algorithms for single graph6
```{r}
library(igraph)
library(parallel)
library(tictoc)

source("src/3-pseudocoloring.R")
source("src/2-coloring.R")
source("src/is_colored_properly.R")
source("src/sum_coloring.R")
source("src/27_26-approximate-coloring.R")
source("src/brute_force.R")
source("src/is_optimal.R")

g <- read.graph("test0407/1-5.graphml", "graphml")
# two_coloring(g, TRUE)
# three_pseudocoloring(g, c, TRUE)
V(g)$color <- 1
plot(g, layout=layout_as_bipartite, main='input graph', vertex.size=40, vertex.label.cex=1, vertex.label = paste(V(g)$name, '/', V(g)$weight))

parts <- decompose(g)
result <- four_coloring(parts[[1]], c)
graph <- result[[1]]
sum <- result[[2]]
  
if(length(parts) > 1) {
  for(i in 2:length(parts)) {
    result <- four_coloring(parts[[i]], c)
    graph <- graph + result[[1]]
    sum <- sum + result[[2]]
  }
}

plot(graph, layout=layout_as_bipartite, palette=diverging_pal(4), main=paste0('approximate:', sum), vertex.size=40, vertex.label.cex=1, vertex.label = paste(V(graph)$name, '/', V(graph)$weight))

# tic('compare algorithms for single graph')
# approximated <- four_coloring(g, c, TRUE)
# bruteForced <- brute_force(g, c, approximated[[2]], TRUE)
# toc()
# 
# print(approximated[[2]] / bruteForced[[2]])
```
# Test 0
```{r}
c <- c(1,2,3,4)
n = 11
g <- sample_bipartite(floor(n/2), ceiling(n/2), p=0.4)
V(g)$weight = sample(c(1,2,6,24), n, replace = TRUE)
V(g)$name <- letters[1:n]

# g <- read.graph("graphs/bipartite.graphml", "graphml")

tic("27/26-approximate")
result <- four_coloring(g, c)
toc()

S <- result[[1]]
Ssum <- result[[2]]
result_print(S, Ssum)

g$sumS <- Ssum

tic("brute_force")
B <- brute_force2(g, c, Ssum)
Bsum <- sum_coloring(B, c)
toc()

result_print(B, Bsum)

g$sumB <- Bsum
g$optimal <- Bsum == Ssum
write_graph(g, "graphs/test1/9_04.graphml", "graphml")

```
# Test 1 - different weight combinations
```{r}
tic('Generating graphs for test1')
weights <- c(1,2,6,24)
for (i in 1:length(weights)**length(V(g))) {
# for (i in 1:2) {
  gtmp <- g
  
  for (j in 1:length(V(gtmp))) {
    V(gtmp)[j]$weight <- 1
  }
  
  write_graph(gtmp, paste0('graphs/test1/', i, '.graphml'), "graphml")
}
toc()
```