---
title: "Tests"
output: html_notebook
---

```{r}
library(igraph)
library(parallel)
library(tictoc)
library(dplyr)

source("../src/3-pseudocoloring.R")
source("../src/2-coloring.R")
source("../src/is_colored_properly.R")
source("../src/sum_coloring.R")
source("../src/27_26-approximate-coloring.R")
source("../src/brute_force.R")
source("../src/test0.R")

source('../generators/edge_sequence.R')

test <- 't2-0502'
path <- paste0('../graphs/', test, '/')

if (!dir.exists(path))
  dir.create(path)

c <- c(1,2,3,4)
df <- data.frame()

graph <- make_empty_graph(n = 8, directed = FALSE)
V(graph)[1:4]$type <- FALSE
V(graph)[5:8]$type <- TRUE
V(graph)$name <- letters[1:8]
V(graph)$weight <- c(1,2,6,24,1,2,6,24)

tic()
for(i in 1:2^16) {
  if (i %% 1000 == 0) {
    print(paste0(Sys.time(), ' -> ', i))
  }
  
  g <- all_edges(graph, i)
  write_graph(g, paste0(path, i , '.graphml'), "graphml")
  
  t0 <- test0(g)
  
  if(t0$result) {
    twoColoring <- two_coloring(g)
    V(g)[twoColoring[[1]]]$color <- c[1]
    V(g)[twoColoring[[2]]]$color <- c[2]
    sumA <- sum_coloring(g, c)
    sumB <- sumA
  } else {
    parts <- decompose(g)
    sumA <- 0
    sumB <- 0
    
    for(k in 1:length(parts)) {
      resultA <- four_coloring(parts[[k]], c)
      V(g)[V(resultA[[1]])$name]$color <- V(resultA[[1]])$color
      sumA <- sumA + resultA[[2]]
    }
    
    resultB <- brute_force(g, c, sumA)
    V(g)$color2 <- V(resultB[[1]])$color
    sumB <- resultB[[2]]
  }
  
  df <- rbind(df, data.frame(list(
    index = i,
    approximated = sumA,
    ratio = sumA / sumB,
    colors = length(unique(V(g)$color)),
    density = length(E(g)) / 16,
    vertices = paste(V(g)$weight, collapse=','),
    edges = paste0(as_ids(E(g)), collapse = ','),
    test0 = t0$result,
    hiss = t0$hiss,
    vas = t0$vas,
    vbs = t0$vbs
  )))
}
toc()
Sys.time()

saveRDS(df, paste0(path, 'data.rds'))
df
```

```{r}
library(igraph)
library(parallel)
library(tictoc)
library(dplyr)

source("../src/3-pseudocoloring.R")
source("../src/2-coloring.R")
source("../src/is_colored_properly.R")
source("../src/sum_coloring.R")
source("../src/27_26-approximate-coloring.R")
source("../src/brute_force.R")
source("../src/test0.R")

test <- 't2-0502'

df <- readRDS(paste0('../graphs/', test, '/data.rds'))

df0 <- dfu[dfu$test0==FALSE,]
df0
print('sifted by test0:')
nrow(df) - nrow(df0)

print('colors')
table(df0$colors)

print('approximated:')
nrow(df0[df0$ratio!=1,])
df0[df0$ratio!=1,]

```

```{r}
library(igraph)
library(parallel)
library(tictoc)
library(dplyr)

source("../src/3-pseudocoloring.R")
source("../src/2-coloring.R")
source("../src/is_colored_properly.R")
source("../src/sum_coloring.R")
source("../src/27_26-approximate-coloring.R")
source("../src/brute_force.R")
source("../src/test0.R")

source('../generators/edge_sequence.R')

c <- c(1,2,3,4)

graph <- make_empty_graph(n = 8, directed = FALSE)
V(graph)[1:4]$type <- FALSE
V(graph)[5:8]$type <- TRUE
V(graph)$name <- letters[1:8]
V(graph)$weight <- c(1,2,6,24,1,2,6,24)

i = 18

g <- all_edges(graph, i)
degree(g)

plot(g, layout=layout_as_bipartite)
```