---
title: "Single graph compa"
output: html_notebook
---

First load all libraries and functions

```{r}
library(igraph)
library(parallel)
library(tictoc)

source("../src/bipartite_two_coloring.R")
source("../src/bipartite_three_pseudocoloring.R")
source("../src/bipartite_four_coloring_approximated.R")

g <- sample_bipartite(10, 10, type='gnp', 0.2)
g <- read_graph('../graphs/bipartite6.graphml', 'graphml')
# V(g)$weight <- 1
colors <- c(1,2,3,4)
bipartite_two_coloring(g, TRUE)
bipartite_three_pseudocoloring(g, colors, TRUE)
bipartite_four_coloring_approximated(g, colors, TRUE)
```
```{r}
library(igraph)
library(parallel)
library(tictoc)

source("../src/bipartite_two_coloring.R")
source("../src/bipartite_three_pseudocoloring.R")

g <- sample_bipartite(10, 10, type='gnp', 0.1)
# g <- read_graph('../graphs/bipartite6.graphml', 'graphml')
V(g)$weight <- 1
colors <- c(1,2,2)

g2 <- bipartite_two_coloring(g, TRUE)
V(g)[g2$v1]$type <- TRUE
V(g)[g2$v2]$type <- FALSE

bipartite_three_pseudocoloring(g, colors, TRUE)
```
```{r}
d <- c(0.001, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.05, 0.1, 0.15, 0.2)

tic()
for(i in 1:length(d)) {
  for(j in 1:2) {
    g <- sample_bipartite(100, 100, type = "gnp", p=d[i])
    bipartite_three_pseudocoloring(g, c(1,2,2))
  }
}
toc()
```
# Approximate algorithm

```{r}
library(igraph)
library(parallel)
library(tictoc)

source("src/3-pseudocoloring.R")
source("src/2-coloring.R")
source("src/is_colored_properly.R")
source("src/sum_coloring.R")
source("src/27_26-approximate-coloring.R")
source("src/brute_force.R")

c <- c(1,2,3,4)
g <- read.graph("test04/5-1.graphml", "graphml")
parts <- decompose(g)
graphA <- g
sumA <- 0

tic('approximate')
for(i in 1:length(parts)) {
  result <- four_coloring(parts[[i]], c)
  V(graphA)[V(result[[1]])$name]$color <- V(result[[1]])$color
  sumA <- sumA + result[[2]]
}
toc()

plot(graphA, layout=layout_as_bipartite, palette=diverging_pal(4), main=paste0('approximate: ', sumA), vertex.size=40, vertex.label.cex=1, vertex.label = paste0(V(graphA)$name, '/', V(graphA)$weight, '/', V(graphA)$color))
```

# Approximate and brute force

```{r}
library(igraph)
library(parallel)
library(tictoc)

source("../src/3-pseudocoloring.R")
source("../src/2-coloring.R")
source("../src/is_colored_properly.R")
source("../src/sum_coloring.R")
source("../src/27_26-approximate-coloring.R")
source("../src/brute_force.R")

graph <- read.graph("../graphs/t1-0502/2.graphml", "graphml")

parts <- decompose(graph)
sumA <- 0
sumB <- 0
   
colors <- c(1,2,3,4)

plot(graph, layout = layout_as_bipartite, vertex.size = 40, vertex.label.cex = 1, vertex.label = paste0(V(graph)$name, '/', V(graph)$weight), vertex.color = 'orange')

tic('compare approximate and brute force')
for(k in 1:length(parts)) {
    resultA <- four_coloring(parts[[k]], c)
    V(graph)[V(resultA[[1]])$name]$color <- V(resultA[[1]])$color
    sumA <- sumA + resultA[[2]]
}
toc()

resultB <- brute_force(graph, c, sumA)
V(graph)$color2 <- V(resultB[[1]])$color
sumB <- resultB[[2]]

plot(graph, layout=layout_as_bipartite, palette=diverging_pal(4), main=paste0('approximate:', sumA), vertex.size=40, vertex.label.cex=1, vertex.label
     = paste0(V(graph)$name, '/', V(graph)$weight, '/', V(graph)$color), vertex.color = V(graph)$color)

plot(graph, layout=layout_as_bipartite, palette=diverging_pal(4), main=paste0('brute force:', sumB), vertex.size=40, vertex.label.cex=1, vertex.label = paste0(V(graph)$name, '/', V(graph)$weight, '/', V(graph)$color2), vertex.color = V(graph)$color2)

```

# Debug

```{r}
library(igraph)
library(parallel)
library(tictoc)

source("src/3-pseudocoloring.R")
source("src/2-coloring.R")
source("src/is_colored_properly.R")
source("src/sum_coloring.R")
source("src/27_26-approximate-coloring.R")
source("src/brute_force.R")

colors <- c(1,2,3,4)
graph <- read.graph("test0427/169.graphml", "graphml")

# graph <- read.graph("graphs/bipartite.graphml", "graphml")

# three_pseudocoloring(graph, colors, TRUE)
# four_coloring(graph, colors)
# brute_force(graph, colors, 0, TRUE)

```


